/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Classes.DB;
import fordesign.RoundedButton;
import fordesign.RoundedPasswordField;
import fordesign.RoundedTextField;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * @author Jake
 * @author Saipoden
 * 
 */
public class Form_Login extends javax.swing.JFrame {

    
    public Form_Login() {
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(null);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox_password = new javax.swing.JCheckBox();
        jButton1 = new RoundedButton(45);
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_close.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setToolTipText("");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 30, 33));

        jLabel_title.setFont(new java.awt.Font("Trebuchet MS", 1, 55)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 212, 60));
        jLabel_title.setText("Login");
        jPanel1.add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 212, 60));
        jLabel_username.setText("Email");
        jPanel1.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jTextField_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username.setText("username");
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 347, -1));

        jLabel_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 212, 60));
        jLabel_password.setText("Password");
        jPanel1.add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 347, -1));

        jCheckBox_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox_password.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_password.setText("Show Password");
        jCheckBox_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 347, 43));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_1.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_passwordActionPerformed
        // show hide password
        if(jCheckBox_password.isSelected())
        {
            jPasswordField1.setEchoChar((char)0);
        }
        else
        {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_passwordActionPerformed

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        
        //close the form
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        
        if(jTextField_username.getText().trim().toLowerCase().equals("username")){
        jTextField_username.setText("");
        jTextField_username.setForeground(Color.black);
        
    }
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        // set text to username if textfield is empty or = username
        if(jTextField_username.getText().trim().toLowerCase().equals("username") || 
            jTextField_username.getText().trim().toLowerCase().equals("") )
        {
            jTextField_username.setText("username");
        jTextField_username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
     
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        
        String password = String.valueOf(jPasswordField1.getPassword()); // get password
        if(password.trim().toLowerCase().equals("password")){
        
        jPasswordField1.setText("");
        jPasswordField1.setForeground(Color.black);
    }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // set text to password if textfield is empty or = password
        String password = String.valueOf(jPasswordField1.getPassword()); //get password
        if(password.trim().toLowerCase().equals("password") || 
            password.trim().toLowerCase().equals("") )
        {
        jPasswordField1.setText("password");
        jPasswordField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        // TODO add your handling code here:
        String username = jTextField_username.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        String query ="SELECT * FROM `users` WHERE `username` = ? AND password = ?";
        
        if(username.trim().toLowerCase().equals("username") || password.trim().toLowerCase().equals("password")){
            JOptionPane.showMessageDialog(null , "Enter a valid username & password" , "Login Failed", 1);
            
        }
        else {
            try {
                 ps = DB.getConnection().prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, password);
            rs = ps.executeQuery();
            
            if (rs.next()){
               // System.out.println("Login");
               Home hm = new Home();
               hm.setVisible(true);
               // hide login form
               this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(null , "Invalid username or password" , "Login Failed", 2);
            }
            }
            catch(SQLException ex){
                try {
                    ps = DB.getConnection().prepareStatement(query);
                } catch (SQLException ex1) {
                    Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex1);
                }
                try {
                    ps.setString(1, username);
                } catch (SQLException ex1) {
                    Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex1);
                }
                try {
                    ps.setString(2, password);
                } catch (SQLException ex1) {
                    Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex1);
                }
                try {
                    rs = ps.executeQuery();
                } catch (SQLException ex1) {
                    Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex1);
                }
            
                try {
                    if (rs.next()){
                        System.out.println("Login");
                    }
                    else {
                        System.out.println(ex.getMessage());
                    }   } catch (SQLException ex1) {
                    Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex1);
                }
                
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_password;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
