/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.BookingHistory;
import Classes.CarAudit;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import java.util.ArrayList;
import javax.swing.JFrame;
import fordesign.RoundedPanel;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ANGEL SHANE
 */
public class Form_VehicleHistory extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * 
     */
    Classes.CarAudit carAudit = new Classes.CarAudit();
   // ArrayList<Classes.Location>locations_list = location.locationList();
      
    public Form_VehicleHistory() {
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        
populateJtableWithCarHistory() ;
    }
    
    public void populateJtableWithCarHistory() {
        ArrayList<Classes.CarAudit> carAuditList = carAudit.getCarAuditList(); // Assuming carAudit is an instance of CarAudit class

    // Define column names
    String[] columnsName = {
        "Audit ID", "Action", "Car ID", "Brand", "Model", "Fuel", "Color", "Plate Number",
        "Passengers", "Gearbox", "Price", "Status", "Action Time"
    };

    // Prepare rows
    Object[][] rows = new Object[carAuditList.size()][columnsName.length];
    for (int i = 0; i < carAuditList.size(); i++) {
        CarAudit c = carAuditList.get(i);
        rows[i][0]  = c.getAuditId();
        rows[i][1]  = c.getAction();
        rows[i][2]  = c.getCarId();
        rows[i][3]  = c.getBrand();
        rows[i][4]  = c.getModel();
        rows[i][5]  = c.getFuel();
        rows[i][6]  = c.getColor();
        rows[i][7]  = c.getPlateNum();
        rows[i][8]  = c.getPassengers();
        rows[i][9]  = c.getGearbox();
        rows[i][10] = c.getPrice();
        rows[i][11] = c.getStatus();
        rows[i][12] = c.getActionTime();
    }

    // Set model to table
    DefaultTableModel model = new DefaultTableModel(rows, columnsName);
    jTable_CarHistory.setModel(model);

    // Optional: Adjust column widths
    jTable_CarHistory.getColumnModel().getColumn(0).setPreferredWidth(60);  // Audit ID
    jTable_CarHistory.getColumnModel().getColumn(1).setPreferredWidth(60);  // Action
    jTable_CarHistory.getColumnModel().getColumn(2).setPreferredWidth(45);  // Car ID
    jTable_CarHistory.getColumnModel().getColumn(3).setPreferredWidth(80); // Brand
    jTable_CarHistory.getColumnModel().getColumn(4).setPreferredWidth(100); // Model
    jTable_CarHistory.getColumnModel().getColumn(5).setPreferredWidth(80);  // Fuel
    jTable_CarHistory.getColumnModel().getColumn(6).setPreferredWidth(60);  // Color
    jTable_CarHistory.getColumnModel().getColumn(7).setPreferredWidth(90); // Plate Number
    jTable_CarHistory.getColumnModel().getColumn(8).setPreferredWidth(80);  // Passengers
    jTable_CarHistory.getColumnModel().getColumn(9).setPreferredWidth(90);  // Gearbox
    jTable_CarHistory.getColumnModel().getColumn(10).setPreferredWidth(80); // Price
    jTable_CarHistory.getColumnModel().getColumn(11).setPreferredWidth(90);
    jTable_CarHistory.getColumnModel().getColumn(12).setPreferredWidth(120);

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanel(15);
        jScrollPane3 = new raven.scroll.win11.ScrollPaneWin11();
        jTable_CarHistory = new javax.swing.JTable();
        jLabel_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(238, 241, 249));
        jPanel1.setOpaque(false);

        jTable_CarHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_CarHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_CarHistory.setToolTipText("");
        jTable_CarHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_CarHistory.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTable_CarHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CarHistoryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_CarHistory);
        jTable_CarHistory.setBackground(new java.awt.Color(255, 255, 255 ));  // White background
        jTable_CarHistory.setSelectionBackground(new java.awt.Color(204,204,204));  // Light blue selection
        jTable_CarHistory.setSelectionForeground(new java.awt.Color(0,0,0));  // White text when selected
        jTable_CarHistory.setGridColor(new java.awt.Color(204, 204, 204));  // Light gray grid lines
        jTable_CarHistory.setForeground(new java.awt.Color(0, 0, 0));  // Black text for the table content
        FlatLaf.registerCustomDefaultsSource("style");
        FlatDarculaLaf.setup();

        jLabel_close.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setToolTipText("");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel_close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_CarHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CarHistoryMouseClicked
        // get the selected car image
    }//GEN-LAST:event_jTable_CarHistoryMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked

        //close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_VehicleHistory().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable_CarHistory;
    // End of variables declaration//GEN-END:variables
}
