/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import fordesign.RoundedPanel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANGEL SHANE
 */
public class Form_Viewcustomer extends javax.swing.JFrame {

    /**
     */
    Classes.Customer customer = new Classes.Customer();
    ArrayList<Classes.Customer>customer_list = customer.CustomerList();
    public Form_Viewcustomer() {
        initComponents();
        setLocationRelativeTo(null);
        populateJtableWithCustomers();
        
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
    }
    
    public void populateJtableWithCustomers() {
    // Clear array List
    customer_list.clear();
    // populate arrayList
    customer_list = customer.CustomerList();
    
    // JTable Columns
    String[] columnsName = {"ID", "full Name","BirthDate","Phone Number","Email","Address"};
    // Rows
    Object[][] rows = new Object[customer_list.size()][columnsName.length];
    
    for (int i = 0; i < customer_list.size(); i++) {
        rows[i][0] = customer_list.get(i).getId();
        rows[i][1] = customer_list.get(i).getFullname();
        rows[i][2] = customer_list.get(i).getBirthdate();
        rows[i][3] = customer_list.get(i).getPhone();
        rows[i][4] = customer_list.get(i).getEmail();
        rows[i][5] = customer_list.get(i).getAddress();
    }

    DefaultTableModel customer = new DefaultTableModel(rows, columnsName);
    jTable_topCustomers.setModel(customer);
    
    // Set column widths manually
    jTable_topCustomers.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
    jTable_topCustomers.getColumnModel().getColumn(1).setPreferredWidth(150); // Full Name
    jTable_topCustomers.getColumnModel().getColumn(2).setPreferredWidth(100); // BirthDate
    jTable_topCustomers.getColumnModel().getColumn(3).setPreferredWidth(115); // Phone Number
    jTable_topCustomers.getColumnModel().getColumn(4).setPreferredWidth(155); // Email
    jTable_topCustomers.getColumnModel().getColumn(5).setPreferredWidth(300); // Address
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanel(15);
        jScrollPane3 = new raven.scroll.win11.ScrollPaneWin11();
        jTable_topCustomers = new javax.swing.JTable();
        jLabel_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(238, 241, 249));
        jPanel1.setOpaque(false);

        jTable_topCustomers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_topCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_topCustomers.setToolTipText("");
        jTable_topCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_topCustomers.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTable_topCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_topCustomersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_topCustomers);
        jTable_topCustomers.setBackground(new java.awt.Color(255, 255, 255 ));  // White background
        jTable_topCustomers.setSelectionBackground(new java.awt.Color(204,204,204));  // Light blue selection
        jTable_topCustomers.setSelectionForeground(new java.awt.Color(0,0,0));  // White text when selected
        jTable_topCustomers.setGridColor(new java.awt.Color(204, 204, 204));  // Light gray grid lines
        jTable_topCustomers.setForeground(new java.awt.Color(0, 0, 0));  // Black text for the table content
        FlatLaf.registerCustomDefaultsSource("style");
        FlatDarculaLaf.setup();

        jLabel_close.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setToolTipText("");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel_close)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked

        //close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jTable_topCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_topCustomersMouseClicked
        // get the selected car image
    }//GEN-LAST:event_jTable_topCustomersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Viewcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Viewcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Viewcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Viewcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        FlatLaf.registerCustomDefaultsSource("raven.table");
//        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Viewcustomer().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_topCustomers;
    // End of variables declaration//GEN-END:variables
}
